### ISSUE TITLE
Quiero agregar mis datos a tu pagina!

### ISSUE THREAD

**Issue by juanvillaf** [xarpdev/devtech-podcast-web#4]
Hola Santiago. Me gustaria formar parte de tu proyecto. Te envío una cap de pantalla con los cambios que sugiero en el issue #4
![image](https://user-images.githubusercontent.com/107740741/179117792-e1562d96-aa76-4ea8-8c0b-81488abe1330.png)
Estaremos en contacto

**Comment by xarpdev** [comment]
Ya está hecho, se cierra este issue.
Muchas gracias por tu aporte!
